[package]
name = "ui4"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# lockfree = { git = "https://gitlab.com/sals3r0/lockfree.git" } # maybe reenable once it compiles
crossbeam-channel = "0.5.1"
slotmap = "1.0"
morphorm = "0.2"
derive_more = "0.99.16"
concat-idents = "1.1.3"
epaint = "0.15.0"
bevy_egui = { path = "../bevy_egui" }
bevy-inspector-egui = { path = "../bevy-inspector-egui" }

ui4-macros = { path = "./ui4-macros" }

[dependencies.bevy]
git = "https://github.com/TheRawMeatball/bevy"
branch = "merge-in-main"
# default-features = false
# features = ["render"]


[patch."https://github.com/bevyengine/bevy"]
bevy = { path = "../bevy" }

[patch."https://github.com/TheRawMeatball/bevy"]
bevy = { path = "../bevy" }

[patch."https://github.com/jakobhellermann/bevy_egui"]
bevy_egui = { path = "../bevy_egui" }
