[package]
name = "ui4"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# lockfree = { git = "https://gitlab.com/sals3r0/lockfree.git" } # maybe reenable once it compiles
crossbeam-channel = "0.5.1"
slotmap = "1.0"
morphorm = { git = "https://github.com/geom3trik/morphorm" }
derive_more = "0.99.16"
concat-idents = "1.1.3"
epaint = "0.15.0"
smallvec = "1"
kdl = "3.0.0"
anyhow = "1.0.44"

ui4-macros = { path = "./ui4-macros" }

[dependencies.bevy]
git = "https://github.com/TheRawMeatball/bevy"
branch = "runs-ui4-migrated"
default-features = false

[dependencies.bevy_egui]
git = "https://github.com/TheRawMeatball/bevy_egui"
branch = "updated-egui"

[dependencies.bevy-inspector-egui]
git = "https://github.com/TheRawMeatball/bevy-inspector-egui"
branch = "runs-ui4"

# Testing patches
[patch."https://github.com/bevyengine/bevy".bevy]
git = "https://github.com/TheRawMeatball/bevy"
branch = "runs-ui4-migrated"

[patch."https://github.com/jakobhellermann/bevy_egui".bevy_egui]
git = "https://github.com/TheRawMeatball/bevy_egui"
branch = "updated-egui"

# Local dev patches

# [patch."https://github.com/bevyengine/bevy"]
# bevy = { path = "../bevy" }

# [patch."https://github.com/TheRawMeatball/bevy"]
# bevy = { path = "../bevy" }

# [patch."https://github.com/jakobhellermann/bevy_egui"]
# bevy_egui = { path = "../bevy_egui" }

# [patch."https://github.com/TheRawMeatball/bevy_egui"]
# bevy_egui = { path = "../bevy_egui" }

# [patch."https://github.com/jakobhellermann/bevy-inspector-egui"]
# bevy-inspector-egui = { path = "../bevy-inspector-egui" }

# [patch."https://github.com/TheRawMeatball/bevy-inspector-egui"]
# bevy-inspector-egui = { path = "../bevy-inspector-egui" }
