[package]
name = "ui4"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# lockfree = { git = "https://gitlab.com/sals3r0/lockfree.git" } # maybe reenable once it compiles
crossbeam-channel = "0.5.1"
slotmap = "1.0"
morphorm = { git = "https://github.com/geom3trik/morphorm" }
derive_more = "0.99.16"
concat-idents = "1.1.3"
smallvec = "1"

fontdue = "0.6.2"

ui4-macros = { path = "./ui4-macros" }

[dependencies.bevy]
git = "https://github.com/TheRawMeatball/bevy"
branch = "merge-in-main"
default-features = false

[dependencies.bevy-inspector-egui]
git = "https://github.com/TheRawMeatball/bevy-inspector-egui"
branch = "runs-ui4-render-attempt"

# Local dev patches

[patch."https://github.com/bevyengine/bevy"]
bevy = { path = "../bevy" }

[patch."https://github.com/TheRawMeatball/bevy"]
bevy = { path = "../bevy" }
