[package]
name = "ui4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# lockfree = { git = "https://gitlab.com/sals3r0/lockfree.git" } # maybe reenable once it compiles
crossbeam-channel = "0.5.1"

[dependencies.bevy]
path = "../bevy"
# default-features = false
# features = ["render"]

[dev-dependencies]
bevy-inspector-egui = { git = "https://github.com/jakobhellermann/bevy-inspector-egui/", branch = "bevy-main" }
derive_more = "0.99.16"

[patch."https://github.com/bevyengine/bevy"]
bevy = { path = "../bevy" }

